// webapp/src/pages/login/index.tsx
import React from 'react';
import './style.css';
import { Form, Input, Button, Checkbox, Card, message } from 'antd';
import axios from '../../request';
import { Redirect } from 'react-router-dom';

const layout = {
  labelCol: { span: 8 },
  wrapperCol: { span: 16 },
};
const tailLayout = {
  wrapperCol: { offset: 8, span: 16 },
};

interface State {
  isLogin: boolean;
}

class Login extends React.Component {

  state = {
    isLogin: false,
  }

  componentDidMount() {
    axios.get('/api/core/isLogin').then((res) => {
        if (res.data) {
            this.setState({
                isLogin: true,
            });
        }
    });
}

  onFinish = (values: any) => {
    console.log('Success:', values);
    axios.post('/api/core/login', { username: values.username, password: values.password }).then((res: any) => {
      if (res.data) {
        this.setState({
          isLogin: true,
        });
        message.success('登陆成功');
      } else {
        message.error(res.errMsg);
      }
    });
  };

  onFinishFailed = (errorInfo: any) => {
    console.log('Failed:', errorInfo);
  };

  render() {
    const { isLogin } = this.state;
    console.log(isLogin);
    if (isLogin) {
      return <Redirect to="/" />
    }
    return (
      <div className="login">
        <Card className="form">
          <div className="title">
            数据管理系统
          </div>
          <Form
            layout="vertical"
            name="basic"
            initialValues={{ remember: true }}
            onFinish={this.onFinish}
            onFinishFailed={this.onFinishFailed}
          >
            <Form.Item
              label="用户名"
              name="username"
              rules={[{ required: true, message: '请输入你的用户名!' }]}
            >
              <Input />
            </Form.Item>

            <Form.Item
              label="密码"
              name="password"
              rules={[{ required: true, message: '请输入你的密码!' }]}
            >
              <Input.Password />
            </Form.Item>

            <Form.Item>
              <Button type="primary" htmlType="submit">
                登陆
          </Button>
            </Form.Item>
          </Form>
        </Card >
      </div>
    );
  }
}

export default Login;

// webapp/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { LoginService } from './login.service';
import { NzMessageService } from 'ng-zorro-antd/message';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  validateForm!: FormGroup;
  loaded = false;

  constructor(
    private fb: FormBuilder,
    private ser: LoginService,
    private message: NzMessageService,
    private router: Router) { }

  ngOnInit(): void {
    this.validateForm = this.fb.group({
      userName: [null, [Validators.required]],
      password: [null, [Validators.required]],
      remember: [true]
    });

    this.ser.isLogin().subscribe((result: any) => {
      if (result.data) {
        this.router.navigate(['/']);
      } else {
        this.loaded = true;
      }
    });
  }

  submitForm(): void {
    for (const i in this.validateForm.controls) {
      this.validateForm.controls[i].markAsDirty();
      this.validateForm.controls[i].updateValueAndValidity();
    }
    if (!this.validateForm.valid) {
      return;
    }
    const postData = {
      username: this.validateForm.value.userName,
      password: this.validateForm.value.password,
    };
    this.ser.login(postData).subscribe((result: any) => {
      if (result.data) {
        this.message.success('登陆成功');
        this.router.navigate(['/']);
      } else {
        this.message.success(result.errMsg);
      }
    });
  }

}

<div class="login" *ngIf="loaded">
    <nz-card class="form">
        <h2>数据管理系统</h2>
        <form nz-form [formGroup]="validateForm" class="login-form" (ngSubmit)="submitForm()">
            <nz-form-item>
              <nz-form-control nzErrorTip="请输入你的用户名!">
                <nz-input-group nzPrefixIcon="user">
                  <input type="text" nz-input formControlName="userName" placeholder="用户名" />
                </nz-input-group>
              </nz-form-control>
            </nz-form-item>
            <nz-form-item>
              <nz-form-control nzErrorTip="请输入你的密码!">
                <nz-input-group nzPrefixIcon="lock">
                  <input type="password" nz-input formControlName="password" placeholder="密码" />
                </nz-input-group>
              </nz-form-control>
            </nz-form-item>
            <div nz-row class="login-form-margin">
              <div nz-col>
                <label nz-checkbox formControlName="remember">
                  <span>记住密码</span>
                </label>
              </div>
            </div>
            <button nz-button class="login-form-button login-form-margin" [nzType]="'primary'">登陆</button>
          </form>
    </nz-card>
</div>
